### ISSUE TITLE
mux: failed to read from packetio.Buffer short buffer

### ISSUE THREAD

**Issue by bigfarts** [murkland/bbn6#16]
```
mux ERROR: 2022/03/24 07:52:03 mux: failed to read from packetio.Buffer short buffer
panic: runtime error: index out of range [20214] with length 2048

goroutine 164 [running]:
github.com/pion/transport/packetio.(*Buffer).Read(0xc0001d0180, {0xc0008e4600, 0x5b4, 0x5b4})
        github.com/pion/transport@v0.13.0/packetio/buffer.go:208 +0x498
github.com/pion/ice/v2.(*Conn).Read(0xc000638030, {0xc0008e4600, 0x5b4, 0x5b4})
        github.com/pion/ice/v2@v2.1.20/transport.go:73 +0x73
github.com/pion/webrtc/v3/internal/mux.(*Mux).readLoop(0xc00062c230)
        github.com/pion/webrtc/v3@v3.1.23/internal/mux/mux.go:109 +0xcb
created by github.com/pion/webrtc/v3/internal/mux.NewMux
        github.com/pion/webrtc/v3@v3.1.23/internal/mux/mux.go:47 +0x165
```

**Comment by bigfarts** [comment]
i've never seen this one again
