### ISSUE TITLE
segfault in github.com/pion/dtls/v2.(*Conn).readAndBuffer

### ISSUE THREAD

**Issue by bigfarts** [murkland/bbn6#23]
```
unexpected fault address 0x292ff2c
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x292ff2c pc=0x104868520]

goroutine 121 [running]:
runtime.throw({0x104dedbd1?, 0x1048191d4?})
	/usr/local/go/src/runtime/panic.go:992 +0x50 fp=0x14000064a50 sp=0x14000064a20 pc=0x104841e10
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:809 +0x1a4 fp=0x14000064a80 sp=0x14000064a50 pc=0x104858064
runtime.(*_type).string(0x292ff04)
	/usr/local/go/src/runtime/type.go:54 +0x20 fp=0x14000064ab0 sp=0x14000064a90 pc=0x104868520
runtime.(*TypeAssertionError).Error(0x140000e89c0)
	/usr/local/go/src/runtime/error.go:39 +0x80 fp=0x14000064bc0 sp=0x14000064ab0 pc=0x104816e80
runtime.preprintpanics(0x140008a86e0?)
	/usr/local/go/src/runtime/panic.go:535 +0x78 fp=0x14000064c30 sp=0x14000064bc0 pc=0x104840ce8
panic({0x104fd0b40, 0x140000e89c0})
	/usr/local/go/src/runtime/panic.go:939 +0x3b4 fp=0x14000064cf0 sp=0x14000064c30 pc=0x104841a64
runtime.panicdottypeE(0x292ff04, 0x104f6fa00, 0x104fb4180)
	/usr/local/go/src/runtime/iface.go:262 +0x70 fp=0x14000064d20 sp=0x14000064cf0 pc=0x1048193e0
github.com/pion/dtls/v2.(*Conn).readAndBuffer(0x14000140700, {0x1050886f8, 0x14000897c80})
	/Users/me/go/pkg/mod/github.com/pion/dtls/v2@v2.1.2/conn.go:558 +0x540 fp=0x14000064e50 sp=0x14000064d20 pc=0x104b2d1b0
github.com/pion/dtls/v2.(*Conn).handshake.func3()
	/Users/me/go/pkg/mod/github.com/pion/dtls/v2@v2.1.2/conn.go:846 +0xc0 fp=0x14000064fd0 sp=0x14000064e50 pc=0x104b2f090
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1259 +0x4 fp=0x14000064fd0 sp=0x14000064fd0 pc=0x104870ee4
created by github.com/pion/dtls/v2.(*Conn).handshake
	/Users/me/go/pkg/mod/github.com/pion/dtls/v2@v2.1.2/conn.go:835 +0x39c
```

**Comment by bigfarts** [comment]
probably the same as #25
